---
#Script options
htmlOutputFileName: index.html
combinedHTMLSlides: mergedHTML.html
slidesPrefixPathnName: sections/slide*.html
templateFileName: mainTemplate.html
#Reveal settings
title: Revealjs as Digital Signage (RDS)
description: Free Digital Signage for Everyone. Start using this tool right now. Revealjs as Digital Signage (RDS) is the easy tool to create Digital Signage.
author: Ali Saleh Baker
theme: sky # black, white, league, beige, sky, night, serif, simple, solarized, blood, moon
#Default settings for our auto-animate transitions, can be overridden per-slide or per-element via data arguments
autoAnimateEasing: "ease"
autoAnimateDuration: 1.0
autoAnimateUnmatched: "true"
transitions: zoom # none, fade, slide, convex, concave, zoom
transitionSpeed: "default" # default/fast/slow
#Transition style for full page slide backgrounds
backgroundTransition: "fade" #none/fade/slide/convex/concave/zoom
#Display presentation control arrows
controls: "false"
#Display a presentation progress bar
progress: "false"
#Global override for autolaying embedded media (video/audio/iframe)
autoPlayMedia: "true" #null, "true", "false"
#Determines where controls appear
controlsLayout: "bottom-right" # "edges", "bottom-right"
#Visibility rule for backwards navigation arrows
controlsBackArrows: "faded" #"faded","hidden","visible"
#Display the page number of the current slide
slideNumber: "false"
#Use 1 based indexing for # links to match slide number (default is zero #based)
hashOneBasedIndex: "true"
#Add the current slide number to the URL hash so that reloading the page/copying the URL will return you to the same slide
hash: "true"
#Flags if we should monitor the hash and change slides accordingly
respondToHashChanges: "true"
#Push each slide change to the browser history.Implies `hash: "true"`
history: "false"
#Enable keyboard shortcuts for navigation
keyboard: "true"
#blocks keyboard events when retuning "false"
keyboardCondition: "null"
#Enable the slide overview mode
overview: "true"
#Vertical centering of slides
center: "true"
#Enables touch navigation on devices with touch input
touch: "true"
#Loop the presentation
loop: "false"
#Randomizes the order of slides each time the presentation loads
shuffle: "false"
#Turns fragments on and off globally
fragments: "true"
#Flags whether to include the current fragment in the URL so that reloading brings you to the same fragment position
fragmentInURL: "true"
#Flags if the presentation is running in an embedded mode
#i.e. contained within a limited portion of the screen
embedded: "false"
#Flags if we should show a help overlay when the question-mark key is pressed
help: "true"
#Flags if it should be possible to pause the presentation (blackout)
pause: "true"
#Flags if speaker notes should be visible to all viewers
showNotes: "false"
#Global override for preloading lazy-loaded iframes
preloadIframes: "null" #null, "true", "false"
#Can be used to globally disable auto-animation
autoAnimate: "true"
#Optionally provide a custom element matcher that will be used to dictate which elements we can animate between.
autoAnimateMatcher: "null"
#Stop auto-sliding after user input
autoSlideStoppable: "true"
#Use this method for navigation when auto-sliding (defaults to navigateNext)
autoSlideMethod: "null"
#Enable slide navigation via mouse wheel
mouseWheel: "false"
#Exposes the reveal.js API through window.postMessage
postMessage: "true"
#Dispatches all reveal.js events to the parent window through postMessage
postMessageEvents: "false"
#Focuses body when page changes visibility to ensure keyboard shortcuts work
focusBodyOnPageVisibilityChange: "true"
#The maximum number of pages a single slide can expand onto when printing to PDF, unlimited by default
pdfMaxPagesPerSlide: Number.POSITIVE_INFINITY
#Prints each fragment on a separate slide
pdfSeparateFragments: "true"
#Offset used to reduce the height of content within exported PDF pages.
pdfPageHeightOffset: -1
#Number of slides away from the current that are visible
viewDistance: 3
#Number of slides away from the current that are visible on mobile
mobileViewDistance: 2
#The display mode that will be used to show slides
display: "block"
#Hide cursor if inactive
hideInactiveCursor: "true"
#Time before the cursor is hidden (in ms)
hideCursorTime: 5000
